version: 'v2.12.0'

services:

  adminer:
    image: adminer
    restart: always
    ports:
      - 5000:8080

  db:
    image: mysql:5.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example